// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: src/system-eye/api/proto/metrics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Interval in milliseconds between metric samples
	IntervalMs int32 `protobuf:"varint,1,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	// Optional filters
	IncludeGpu       bool `protobuf:"varint,2,opt,name=include_gpu,json=includeGpu,proto3" json:"include_gpu,omitempty"`
	IncludeProcesses bool `protobuf:"varint,3,opt,name=include_processes,json=includeProcesses,proto3" json:"include_processes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *StreamRequest) GetIncludeGpu() bool {
	if x != nil {
		return x.IncludeGpu
	}
	return false
}

func (x *StreamRequest) GetIncludeProcesses() bool {
	if x != nil {
		return x.IncludeProcesses
	}
	return false
}

type MetricsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IncludeGpu       bool                   `protobuf:"varint,1,opt,name=include_gpu,json=includeGpu,proto3" json:"include_gpu,omitempty"`
	IncludeProcesses bool                   `protobuf:"varint,2,opt,name=include_processes,json=includeProcesses,proto3" json:"include_processes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *MetricsRequest) GetIncludeGpu() bool {
	if x != nil {
		return x.IncludeGpu
	}
	return false
}

func (x *MetricsRequest) GetIncludeProcesses() bool {
	if x != nil {
		return x.IncludeProcesses
	}
	return false
}

type SystemMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Cpu           *CPUMetrics            `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        *MemoryMetrics         `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Disk          *DiskMetrics           `protobuf:"bytes,4,opt,name=disk,proto3" json:"disk,omitempty"`
	Network       *NetworkMetrics        `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	Gpu           *GPUMetrics            `protobuf:"bytes,6,opt,name=gpu,proto3,oneof" json:"gpu,omitempty"`             // Optional - only if GPU available
	Processes     *ProcessMetrics        `protobuf:"bytes,7,opt,name=processes,proto3,oneof" json:"processes,omitempty"` // ^ Optional - process monitoring with deadlock detection fields
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *SystemMetrics) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *SystemMetrics) GetCpu() *CPUMetrics {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *SystemMetrics) GetMemory() *MemoryMetrics {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *SystemMetrics) GetDisk() *DiskMetrics {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *SystemMetrics) GetNetwork() *NetworkMetrics {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *SystemMetrics) GetGpu() *GPUMetrics {
	if x != nil {
		return x.Gpu
	}
	return nil
}

func (x *SystemMetrics) GetProcesses() *ProcessMetrics {
	if x != nil {
		return x.Processes
	}
	return nil
}

type CPUMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Overall         float64                `protobuf:"fixed64,1,opt,name=overall,proto3" json:"overall,omitempty"`                        // Overall CPU usage percentage
	PerCore         []float64              `protobuf:"fixed64,2,rep,packed,name=per_core,json=perCore,proto3" json:"per_core,omitempty"`  // Per-core usage percentages
	LoadAvg_1       float64                `protobuf:"fixed64,3,opt,name=load_avg_1,json=loadAvg1,proto3" json:"load_avg_1,omitempty"`    // 1-minute load average
	LoadAvg_5       float64                `protobuf:"fixed64,4,opt,name=load_avg_5,json=loadAvg5,proto3" json:"load_avg_5,omitempty"`    // 5-minute load average
	LoadAvg_15      float64                `protobuf:"fixed64,5,opt,name=load_avg_15,json=loadAvg15,proto3" json:"load_avg_15,omitempty"` // 15-minute load average
	ContextSwitches uint64                 `protobuf:"varint,6,opt,name=context_switches,json=contextSwitches,proto3" json:"context_switches,omitempty"`
	Interrupts      uint64                 `protobuf:"varint,7,opt,name=interrupts,proto3" json:"interrupts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CPUMetrics) Reset() {
	*x = CPUMetrics{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUMetrics) ProtoMessage() {}

func (x *CPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUMetrics.ProtoReflect.Descriptor instead.
func (*CPUMetrics) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *CPUMetrics) GetOverall() float64 {
	if x != nil {
		return x.Overall
	}
	return 0
}

func (x *CPUMetrics) GetPerCore() []float64 {
	if x != nil {
		return x.PerCore
	}
	return nil
}

func (x *CPUMetrics) GetLoadAvg_1() float64 {
	if x != nil {
		return x.LoadAvg_1
	}
	return 0
}

func (x *CPUMetrics) GetLoadAvg_5() float64 {
	if x != nil {
		return x.LoadAvg_5
	}
	return 0
}

func (x *CPUMetrics) GetLoadAvg_15() float64 {
	if x != nil {
		return x.LoadAvg_15
	}
	return 0
}

func (x *CPUMetrics) GetContextSwitches() uint64 {
	if x != nil {
		return x.ContextSwitches
	}
	return 0
}

func (x *CPUMetrics) GetInterrupts() uint64 {
	if x != nil {
		return x.Interrupts
	}
	return 0
}

type MemoryMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`                                    // Total memory in bytes
	Used          uint64                 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`                                      // Used memory in bytes
	Free          uint64                 `protobuf:"varint,3,opt,name=free,proto3" json:"free,omitempty"`                                      // Free memory in bytes
	Available     uint64                 `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`                            // Available memory in bytes
	Cached        uint64                 `protobuf:"varint,5,opt,name=cached,proto3" json:"cached,omitempty"`                                  // Cached memory in bytes
	Buffers       uint64                 `protobuf:"varint,6,opt,name=buffers,proto3" json:"buffers,omitempty"`                                // Buffer memory in bytes
	UsagePercent  float64                `protobuf:"fixed64,7,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"` // Memory usage as percentage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryMetrics) Reset() {
	*x = MemoryMetrics{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryMetrics) ProtoMessage() {}

func (x *MemoryMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryMetrics.ProtoReflect.Descriptor instead.
func (*MemoryMetrics) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *MemoryMetrics) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *MemoryMetrics) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *MemoryMetrics) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *MemoryMetrics) GetAvailable() uint64 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *MemoryMetrics) GetCached() uint64 {
	if x != nil {
		return x.Cached
	}
	return 0
}

func (x *MemoryMetrics) GetBuffers() uint64 {
	if x != nil {
		return x.Buffers
	}
	return 0
}

func (x *MemoryMetrics) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

type DiskMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DiskDevice          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	Total         *DiskIO                `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"` // Aggregated across all devices
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskMetrics) Reset() {
	*x = DiskMetrics{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskMetrics) ProtoMessage() {}

func (x *DiskMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskMetrics.ProtoReflect.Descriptor instead.
func (*DiskMetrics) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *DiskMetrics) GetDevices() []*DiskDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *DiskMetrics) GetTotal() *DiskIO {
	if x != nil {
		return x.Total
	}
	return nil
}

type DiskDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Device name (e.g., "sda", "nvme0n1")
	Io            *DiskIO                `protobuf:"bytes,2,opt,name=io,proto3" json:"io,omitempty"`     // I/O statistics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskDevice) Reset() {
	*x = DiskDevice{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskDevice) ProtoMessage() {}

func (x *DiskDevice) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskDevice.ProtoReflect.Descriptor instead.
func (*DiskDevice) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *DiskDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DiskDevice) GetIo() *DiskIO {
	if x != nil {
		return x.Io
	}
	return nil
}

type DiskIO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReadBytes     uint64                 `protobuf:"varint,1,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`                 // Bytes read
	WriteBytes    uint64                 `protobuf:"varint,2,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`              // Bytes written
	ReadOps       uint64                 `protobuf:"varint,3,opt,name=read_ops,json=readOps,proto3" json:"read_ops,omitempty"`                       // Read operations
	WriteOps      uint64                 `protobuf:"varint,4,opt,name=write_ops,json=writeOps,proto3" json:"write_ops,omitempty"`                    // Write operations
	ReadLatency   *float64               `protobuf:"fixed64,5,opt,name=read_latency,json=readLatency,proto3,oneof" json:"read_latency,omitempty"`    // Average read latency (ms)
	WriteLatency  *float64               `protobuf:"fixed64,6,opt,name=write_latency,json=writeLatency,proto3,oneof" json:"write_latency,omitempty"` // Average write latency (ms)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskIO) Reset() {
	*x = DiskIO{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskIO) ProtoMessage() {}

func (x *DiskIO) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskIO.ProtoReflect.Descriptor instead.
func (*DiskIO) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *DiskIO) GetReadBytes() uint64 {
	if x != nil {
		return x.ReadBytes
	}
	return 0
}

func (x *DiskIO) GetWriteBytes() uint64 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

func (x *DiskIO) GetReadOps() uint64 {
	if x != nil {
		return x.ReadOps
	}
	return 0
}

func (x *DiskIO) GetWriteOps() uint64 {
	if x != nil {
		return x.WriteOps
	}
	return 0
}

func (x *DiskIO) GetReadLatency() float64 {
	if x != nil && x.ReadLatency != nil {
		return *x.ReadLatency
	}
	return 0
}

func (x *DiskIO) GetWriteLatency() float64 {
	if x != nil && x.WriteLatency != nil {
		return *x.WriteLatency
	}
	return 0
}

type NetworkMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []*NetworkInterface    `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Total         *NetworkTraffic        `protobuf:"bytes,2,opt,name=total,proto3" json:"total,omitempty"` // Aggregated across all interfaces
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMetrics) Reset() {
	*x = NetworkMetrics{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMetrics) ProtoMessage() {}

func (x *NetworkMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMetrics.ProtoReflect.Descriptor instead.
func (*NetworkMetrics) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkMetrics) GetInterfaces() []*NetworkInterface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *NetworkMetrics) GetTotal() *NetworkTraffic {
	if x != nil {
		return x.Total
	}
	return nil
}

type NetworkInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`       // Interface name (e.g., "eth0", "lo")
	Traffic       *NetworkTraffic        `protobuf:"bytes,2,opt,name=traffic,proto3" json:"traffic,omitempty"` // Traffic statistics
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkInterface) Reset() {
	*x = NetworkInterface{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInterface) ProtoMessage() {}

func (x *NetworkInterface) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInterface.ProtoReflect.Descriptor instead.
func (*NetworkInterface) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{9}
}

func (x *NetworkInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkInterface) GetTraffic() *NetworkTraffic {
	if x != nil {
		return x.Traffic
	}
	return nil
}

type NetworkTraffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RxBytes       uint64                 `protobuf:"varint,1,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`       // Bytes received
	TxBytes       uint64                 `protobuf:"varint,2,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`       // Bytes transmitted
	RxPackets     uint64                 `protobuf:"varint,3,opt,name=rx_packets,json=rxPackets,proto3" json:"rx_packets,omitempty"` // Packets received
	TxPackets     uint64                 `protobuf:"varint,4,opt,name=tx_packets,json=txPackets,proto3" json:"tx_packets,omitempty"` // Packets transmitted
	RxErrors      uint64                 `protobuf:"varint,5,opt,name=rx_errors,json=rxErrors,proto3" json:"rx_errors,omitempty"`    // Receive errors
	TxErrors      uint64                 `protobuf:"varint,6,opt,name=tx_errors,json=txErrors,proto3" json:"tx_errors,omitempty"`    // Transmit errors
	RxDropped     uint64                 `protobuf:"varint,7,opt,name=rx_dropped,json=rxDropped,proto3" json:"rx_dropped,omitempty"` // Received packets dropped
	TxDropped     uint64                 `protobuf:"varint,8,opt,name=tx_dropped,json=txDropped,proto3" json:"tx_dropped,omitempty"` // Transmitted packets dropped
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkTraffic) Reset() {
	*x = NetworkTraffic{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkTraffic) ProtoMessage() {}

func (x *NetworkTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkTraffic.ProtoReflect.Descriptor instead.
func (*NetworkTraffic) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{10}
}

func (x *NetworkTraffic) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NetworkTraffic) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *NetworkTraffic) GetRxPackets() uint64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *NetworkTraffic) GetTxPackets() uint64 {
	if x != nil {
		return x.TxPackets
	}
	return 0
}

func (x *NetworkTraffic) GetRxErrors() uint64 {
	if x != nil {
		return x.RxErrors
	}
	return 0
}

func (x *NetworkTraffic) GetTxErrors() uint64 {
	if x != nil {
		return x.TxErrors
	}
	return 0
}

func (x *NetworkTraffic) GetRxDropped() uint64 {
	if x != nil {
		return x.RxDropped
	}
	return 0
}

func (x *NetworkTraffic) GetTxDropped() uint64 {
	if x != nil {
		return x.TxDropped
	}
	return 0
}

type GPUMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*GPUDevice           `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUMetrics) Reset() {
	*x = GPUMetrics{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUMetrics) ProtoMessage() {}

func (x *GPUMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUMetrics.ProtoReflect.Descriptor instead.
func (*GPUMetrics) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{11}
}

func (x *GPUMetrics) GetDevices() []*GPUDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type GPUDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`                             // GPU index
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                // GPU name/model
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`                                // GPU UUID
	Utilization   int32                  `protobuf:"varint,4,opt,name=utilization,proto3" json:"utilization,omitempty"`                 // GPU utilization percentage
	Memory        *GPUMemory             `protobuf:"bytes,5,opt,name=memory,proto3" json:"memory,omitempty"`                            // Memory information
	Temperature   int32                  `protobuf:"varint,6,opt,name=temperature,proto3" json:"temperature,omitempty"`                 // GPU temperature (°C)
	PowerUsage    int32                  `protobuf:"varint,7,opt,name=power_usage,json=powerUsage,proto3" json:"power_usage,omitempty"` // Power usage (watts)
	FanSpeed      int32                  `protobuf:"varint,8,opt,name=fan_speed,json=fanSpeed,proto3" json:"fan_speed,omitempty"`       // Fan speed percentage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUDevice) Reset() {
	*x = GPUDevice{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUDevice) ProtoMessage() {}

func (x *GPUDevice) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUDevice.ProtoReflect.Descriptor instead.
func (*GPUDevice) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{12}
}

func (x *GPUDevice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *GPUDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GPUDevice) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GPUDevice) GetUtilization() int32 {
	if x != nil {
		return x.Utilization
	}
	return 0
}

func (x *GPUDevice) GetMemory() *GPUMemory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *GPUDevice) GetTemperature() int32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GPUDevice) GetPowerUsage() int32 {
	if x != nil {
		return x.PowerUsage
	}
	return 0
}

func (x *GPUDevice) GetFanSpeed() int32 {
	if x != nil {
		return x.FanSpeed
	}
	return 0
}

type GPUMemory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`                                    // Total memory in bytes
	Used          uint64                 `protobuf:"varint,2,opt,name=used,proto3" json:"used,omitempty"`                                      // Used memory in bytes
	Free          uint64                 `protobuf:"varint,3,opt,name=free,proto3" json:"free,omitempty"`                                      // Free memory in bytes
	UsagePercent  float64                `protobuf:"fixed64,4,opt,name=usage_percent,json=usagePercent,proto3" json:"usage_percent,omitempty"` // Memory usage percentage
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GPUMemory) Reset() {
	*x = GPUMemory{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPUMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPUMemory) ProtoMessage() {}

func (x *GPUMemory) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPUMemory.ProtoReflect.Descriptor instead.
func (*GPUMemory) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{13}
}

func (x *GPUMemory) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GPUMemory) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *GPUMemory) GetFree() uint64 {
	if x != nil {
		return x.Free
	}
	return 0
}

func (x *GPUMemory) GetUsagePercent() float64 {
	if x != nil {
		return x.UsagePercent
	}
	return 0
}

type ProcessMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	TopCpu        []*ProcessInfo         `protobuf:"bytes,2,rep,name=top_cpu,json=topCpu,proto3" json:"top_cpu,omitempty"`          // Top CPU consuming processes
	TopMemory     []*ProcessInfo         `protobuf:"bytes,3,rep,name=top_memory,json=topMemory,proto3" json:"top_memory,omitempty"` // Top memory consuming processes
	TopGpu        []*ProcessInfo         `protobuf:"bytes,4,rep,name=top_gpu,json=topGpu,proto3" json:"top_gpu,omitempty"`          // Top GPU using processes (optional)
	TotalCount    int32                  `protobuf:"varint,5,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	RunningCount  int32                  `protobuf:"varint,6,opt,name=running_count,json=runningCount,proto3" json:"running_count,omitempty"`
	SleepingCount int32                  `protobuf:"varint,7,opt,name=sleeping_count,json=sleepingCount,proto3" json:"sleeping_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMetrics) Reset() {
	*x = ProcessMetrics{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMetrics) ProtoMessage() {}

func (x *ProcessMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMetrics.ProtoReflect.Descriptor instead.
func (*ProcessMetrics) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessMetrics) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

func (x *ProcessMetrics) GetTopCpu() []*ProcessInfo {
	if x != nil {
		return x.TopCpu
	}
	return nil
}

func (x *ProcessMetrics) GetTopMemory() []*ProcessInfo {
	if x != nil {
		return x.TopMemory
	}
	return nil
}

func (x *ProcessMetrics) GetTopGpu() []*ProcessInfo {
	if x != nil {
		return x.TopGpu
	}
	return nil
}

func (x *ProcessMetrics) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ProcessMetrics) GetRunningCount() int32 {
	if x != nil {
		return x.RunningCount
	}
	return 0
}

func (x *ProcessMetrics) GetSleepingCount() int32 {
	if x != nil {
		return x.SleepingCount
	}
	return 0
}

type ProcessInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Pid             uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	Ppid            uint32                 `protobuf:"varint,2,opt,name=ppid,proto3" json:"ppid,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Command         *string                `protobuf:"bytes,4,opt,name=command,proto3,oneof" json:"command,omitempty"`
	State           string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	CpuPercent      float64                `protobuf:"fixed64,6,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryPercent   float64                `protobuf:"fixed64,7,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	MemoryRss       uint64                 `protobuf:"varint,8,opt,name=memory_rss,json=memoryRss,proto3" json:"memory_rss,omitempty"`             // Resident Set Size in bytes
	MemoryVirtual   uint64                 `protobuf:"varint,9,opt,name=memory_virtual,json=memoryVirtual,proto3" json:"memory_virtual,omitempty"` // Virtual memory size in bytes
	NumThreads      uint32                 `protobuf:"varint,10,opt,name=num_threads,json=numThreads,proto3" json:"num_threads,omitempty"`
	ReadBytes       uint64                 `protobuf:"varint,11,opt,name=read_bytes,json=readBytes,proto3" json:"read_bytes,omitempty"`
	WriteBytes      uint64                 `protobuf:"varint,12,opt,name=write_bytes,json=writeBytes,proto3" json:"write_bytes,omitempty"`
	OpenFiles       *uint32                `protobuf:"varint,13,opt,name=open_files,json=openFiles,proto3,oneof" json:"open_files,omitempty"`
	SyscallCount    *uint64                `protobuf:"varint,14,opt,name=syscall_count,json=syscallCount,proto3,oneof" json:"syscall_count,omitempty"`
	ContextSwitches *uint64                `protobuf:"varint,15,opt,name=context_switches,json=contextSwitches,proto3,oneof" json:"context_switches,omitempty"`
	GpuMemory       *uint64                `protobuf:"varint,16,opt,name=gpu_memory,json=gpuMemory,proto3,oneof" json:"gpu_memory,omitempty"`                 // GPU memory usage if applicable
	GpuUtilization  *float64               `protobuf:"fixed64,17,opt,name=gpu_utilization,json=gpuUtilization,proto3,oneof" json:"gpu_utilization,omitempty"` // GPU utilization if applicable
	// ========================================================================
	// Deadlock Detection Fields
	// ========================================================================
	WaitChannel *string `protobuf:"bytes,18,opt,name=wait_channel,json=waitChannel,proto3,oneof" json:"wait_channel,omitempty"` // Kernel wait channel (wchan)
	// - what the process is waiting on
	WaitState *string `protobuf:"bytes,19,opt,name=wait_state,json=waitState,proto3,oneof" json:"wait_state,omitempty"` // D (uninterruptible), S (sleeping), R
	// (running), Z (zombie), T (stopped)
	WaitTimeMs           *uint64     `protobuf:"varint,20,opt,name=wait_time_ms,json=waitTimeMs,proto3,oneof" json:"wait_time_ms,omitempty"`                               // Time spent in current state
	HeldLocks            []*FileLock `protobuf:"bytes,21,rep,name=held_locks,json=heldLocks,proto3" json:"held_locks,omitempty"`                                           // File locks held by this process
	WaitingLocks         []*FileLock `protobuf:"bytes,22,rep,name=waiting_locks,json=waitingLocks,proto3" json:"waiting_locks,omitempty"`                                  // File locks this process is
	BlockedThreads       *uint32     `protobuf:"varint,23,opt,name=blocked_threads,json=blockedThreads,proto3,oneof" json:"blocked_threads,omitempty"`                     // Number of blocked threads
	VoluntaryCtxSwitches *uint64     `protobuf:"varint,24,opt,name=voluntary_ctx_switches,json=voluntaryCtxSwitches,proto3,oneof" json:"voluntary_ctx_switches,omitempty"` // Voluntary context switches #
	// (waiting for I/O)
	InvoluntaryCtxSwitches *uint64  `protobuf:"varint,25,opt,name=involuntary_ctx_switches,json=involuntaryCtxSwitches,proto3,oneof" json:"involuntary_ctx_switches,omitempty"` // Involuntary context switches
	WaitingOnPid           *uint32  `protobuf:"varint,26,opt,name=waiting_on_pid,json=waitingOnPid,proto3,oneof" json:"waiting_on_pid,omitempty"`                               // PID this process is blocked by
	BlockingPids           []uint32 `protobuf:"varint,27,rep,packed,name=blocking_pids,json=blockingPids,proto3" json:"blocking_pids,omitempty"`                                // PIDs that are blocked by this process
	CurrentSyscall         *string  `protobuf:"bytes,28,opt,name=current_syscall,json=currentSyscall,proto3,oneof" json:"current_syscall,omitempty"`                            // Current system call being executed
	SyscallDurationMs      *uint64  `protobuf:"varint,29,opt,name=syscall_duration_ms,json=syscallDurationMs,proto3,oneof" json:"syscall_duration_ms,omitempty"`                // How long the syscall has been
	IoWaitTimeMs           *uint64  `protobuf:"varint,30,opt,name=io_wait_time_ms,json=ioWaitTimeMs,proto3,oneof" json:"io_wait_time_ms,omitempty"`                             // Time spent waiting for I/O
	CpuTimeDelta           *uint64  `protobuf:"varint,31,opt,name=cpu_time_delta,json=cpuTimeDelta,proto3,oneof" json:"cpu_time_delta,omitempty"`                               // Change in CPU time since last
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{15}
}

func (x *ProcessInfo) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ProcessInfo) GetPpid() uint32 {
	if x != nil {
		return x.Ppid
	}
	return 0
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetCommand() string {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return ""
}

func (x *ProcessInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ProcessInfo) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *ProcessInfo) GetMemoryRss() uint64 {
	if x != nil {
		return x.MemoryRss
	}
	return 0
}

func (x *ProcessInfo) GetMemoryVirtual() uint64 {
	if x != nil {
		return x.MemoryVirtual
	}
	return 0
}

func (x *ProcessInfo) GetNumThreads() uint32 {
	if x != nil {
		return x.NumThreads
	}
	return 0
}

func (x *ProcessInfo) GetReadBytes() uint64 {
	if x != nil {
		return x.ReadBytes
	}
	return 0
}

func (x *ProcessInfo) GetWriteBytes() uint64 {
	if x != nil {
		return x.WriteBytes
	}
	return 0
}

func (x *ProcessInfo) GetOpenFiles() uint32 {
	if x != nil && x.OpenFiles != nil {
		return *x.OpenFiles
	}
	return 0
}

func (x *ProcessInfo) GetSyscallCount() uint64 {
	if x != nil && x.SyscallCount != nil {
		return *x.SyscallCount
	}
	return 0
}

func (x *ProcessInfo) GetContextSwitches() uint64 {
	if x != nil && x.ContextSwitches != nil {
		return *x.ContextSwitches
	}
	return 0
}

func (x *ProcessInfo) GetGpuMemory() uint64 {
	if x != nil && x.GpuMemory != nil {
		return *x.GpuMemory
	}
	return 0
}

func (x *ProcessInfo) GetGpuUtilization() float64 {
	if x != nil && x.GpuUtilization != nil {
		return *x.GpuUtilization
	}
	return 0
}

func (x *ProcessInfo) GetWaitChannel() string {
	if x != nil && x.WaitChannel != nil {
		return *x.WaitChannel
	}
	return ""
}

func (x *ProcessInfo) GetWaitState() string {
	if x != nil && x.WaitState != nil {
		return *x.WaitState
	}
	return ""
}

func (x *ProcessInfo) GetWaitTimeMs() uint64 {
	if x != nil && x.WaitTimeMs != nil {
		return *x.WaitTimeMs
	}
	return 0
}

func (x *ProcessInfo) GetHeldLocks() []*FileLock {
	if x != nil {
		return x.HeldLocks
	}
	return nil
}

func (x *ProcessInfo) GetWaitingLocks() []*FileLock {
	if x != nil {
		return x.WaitingLocks
	}
	return nil
}

func (x *ProcessInfo) GetBlockedThreads() uint32 {
	if x != nil && x.BlockedThreads != nil {
		return *x.BlockedThreads
	}
	return 0
}

func (x *ProcessInfo) GetVoluntaryCtxSwitches() uint64 {
	if x != nil && x.VoluntaryCtxSwitches != nil {
		return *x.VoluntaryCtxSwitches
	}
	return 0
}

func (x *ProcessInfo) GetInvoluntaryCtxSwitches() uint64 {
	if x != nil && x.InvoluntaryCtxSwitches != nil {
		return *x.InvoluntaryCtxSwitches
	}
	return 0
}

func (x *ProcessInfo) GetWaitingOnPid() uint32 {
	if x != nil && x.WaitingOnPid != nil {
		return *x.WaitingOnPid
	}
	return 0
}

func (x *ProcessInfo) GetBlockingPids() []uint32 {
	if x != nil {
		return x.BlockingPids
	}
	return nil
}

func (x *ProcessInfo) GetCurrentSyscall() string {
	if x != nil && x.CurrentSyscall != nil {
		return *x.CurrentSyscall
	}
	return ""
}

func (x *ProcessInfo) GetSyscallDurationMs() uint64 {
	if x != nil && x.SyscallDurationMs != nil {
		return *x.SyscallDurationMs
	}
	return 0
}

func (x *ProcessInfo) GetIoWaitTimeMs() uint64 {
	if x != nil && x.IoWaitTimeMs != nil {
		return *x.IoWaitTimeMs
	}
	return 0
}

func (x *ProcessInfo) GetCpuTimeDelta() uint64 {
	if x != nil && x.CpuTimeDelta != nil {
		return *x.CpuTimeDelta
	}
	return 0
}

type FileLock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`                         // File path being locked
	LockType      string                 `protobuf:"bytes,2,opt,name=lock_type,json=lockType,proto3" json:"lock_type,omitempty"` // "READ", "WRITE", "ADVISORY", "MANDATORY"
	Inode         uint64                 `protobuf:"varint,3,opt,name=inode,proto3" json:"inode,omitempty"`                      // File inode number
	Pid           uint32                 `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`                          // Process holding/waiting for the lock
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileLock) Reset() {
	*x = FileLock{}
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLock) ProtoMessage() {}

func (x *FileLock) ProtoReflect() protoreflect.Message {
	mi := &file_src_system_eye_api_proto_metrics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLock.ProtoReflect.Descriptor instead.
func (*FileLock) Descriptor() ([]byte, []int) {
	return file_src_system_eye_api_proto_metrics_proto_rawDescGZIP(), []int{16}
}

func (x *FileLock) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileLock) GetLockType() string {
	if x != nil {
		return x.LockType
	}
	return ""
}

func (x *FileLock) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *FileLock) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

var File_src_system_eye_api_proto_metrics_proto protoreflect.FileDescriptor

const file_src_system_eye_api_proto_metrics_proto_rawDesc = "" +
	"\n" +
	"%src/system-eye/api/proto/metrics.proto\x12\ametrics\x1a\x1fgoogle/protobuf/timestamp.proto\"~\n" +
	"\rStreamRequest\x12\x1f\n" +
	"\vinterval_ms\x18\x01 \x01(\x05R\n" +
	"intervalMs\x12\x1f\n" +
	"\vinclude_gpu\x18\x02 \x01(\bR\n" +
	"includeGpu\x12+\n" +
	"\x11include_processes\x18\x03 \x01(\bR\x10includeProcesses\"^\n" +
	"\x0eMetricsRequest\x12\x1f\n" +
	"\vinclude_gpu\x18\x01 \x01(\bR\n" +
	"includeGpu\x12+\n" +
	"\x11include_processes\x18\x02 \x01(\bR\x10includeProcesses\"\xfb\x02\n" +
	"\rSystemMetrics\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12%\n" +
	"\x03cpu\x18\x02 \x01(\v2\x13.metrics.CPUMetricsR\x03cpu\x12.\n" +
	"\x06memory\x18\x03 \x01(\v2\x16.metrics.MemoryMetricsR\x06memory\x12(\n" +
	"\x04disk\x18\x04 \x01(\v2\x14.metrics.DiskMetricsR\x04disk\x121\n" +
	"\anetwork\x18\x05 \x01(\v2\x17.metrics.NetworkMetricsR\anetwork\x12*\n" +
	"\x03gpu\x18\x06 \x01(\v2\x13.metrics.GPUMetricsH\x00R\x03gpu\x88\x01\x01\x12:\n" +
	"\tprocesses\x18\a \x01(\v2\x17.metrics.ProcessMetricsH\x01R\tprocesses\x88\x01\x01B\x06\n" +
	"\x04_gpuB\f\n" +
	"\n" +
	"_processes\"\xe8\x01\n" +
	"\n" +
	"CPUMetrics\x12\x18\n" +
	"\aoverall\x18\x01 \x01(\x01R\aoverall\x12\x19\n" +
	"\bper_core\x18\x02 \x03(\x01R\aperCore\x12\x1c\n" +
	"\n" +
	"load_avg_1\x18\x03 \x01(\x01R\bloadAvg1\x12\x1c\n" +
	"\n" +
	"load_avg_5\x18\x04 \x01(\x01R\bloadAvg5\x12\x1e\n" +
	"\vload_avg_15\x18\x05 \x01(\x01R\tloadAvg15\x12)\n" +
	"\x10context_switches\x18\x06 \x01(\x04R\x0fcontextSwitches\x12\x1e\n" +
	"\n" +
	"interrupts\x18\a \x01(\x04R\n" +
	"interrupts\"\xc2\x01\n" +
	"\rMemoryMetrics\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x03 \x01(\x04R\x04free\x12\x1c\n" +
	"\tavailable\x18\x04 \x01(\x04R\tavailable\x12\x16\n" +
	"\x06cached\x18\x05 \x01(\x04R\x06cached\x12\x18\n" +
	"\abuffers\x18\x06 \x01(\x04R\abuffers\x12#\n" +
	"\rusage_percent\x18\a \x01(\x01R\fusagePercent\"c\n" +
	"\vDiskMetrics\x12-\n" +
	"\adevices\x18\x01 \x03(\v2\x13.metrics.DiskDeviceR\adevices\x12%\n" +
	"\x05total\x18\x02 \x01(\v2\x0f.metrics.DiskIOR\x05total\"A\n" +
	"\n" +
	"DiskDevice\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\x02io\x18\x02 \x01(\v2\x0f.metrics.DiskIOR\x02io\"\xf5\x01\n" +
	"\x06DiskIO\x12\x1d\n" +
	"\n" +
	"read_bytes\x18\x01 \x01(\x04R\treadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18\x02 \x01(\x04R\n" +
	"writeBytes\x12\x19\n" +
	"\bread_ops\x18\x03 \x01(\x04R\areadOps\x12\x1b\n" +
	"\twrite_ops\x18\x04 \x01(\x04R\bwriteOps\x12&\n" +
	"\fread_latency\x18\x05 \x01(\x01H\x00R\vreadLatency\x88\x01\x01\x12(\n" +
	"\rwrite_latency\x18\x06 \x01(\x01H\x01R\fwriteLatency\x88\x01\x01B\x0f\n" +
	"\r_read_latencyB\x10\n" +
	"\x0e_write_latency\"z\n" +
	"\x0eNetworkMetrics\x129\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\v2\x19.metrics.NetworkInterfaceR\n" +
	"interfaces\x12-\n" +
	"\x05total\x18\x02 \x01(\v2\x17.metrics.NetworkTrafficR\x05total\"Y\n" +
	"\x10NetworkInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\atraffic\x18\x02 \x01(\v2\x17.metrics.NetworkTrafficR\atraffic\"\xfc\x01\n" +
	"\x0eNetworkTraffic\x12\x19\n" +
	"\brx_bytes\x18\x01 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x02 \x01(\x04R\atxBytes\x12\x1d\n" +
	"\n" +
	"rx_packets\x18\x03 \x01(\x04R\trxPackets\x12\x1d\n" +
	"\n" +
	"tx_packets\x18\x04 \x01(\x04R\ttxPackets\x12\x1b\n" +
	"\trx_errors\x18\x05 \x01(\x04R\brxErrors\x12\x1b\n" +
	"\ttx_errors\x18\x06 \x01(\x04R\btxErrors\x12\x1d\n" +
	"\n" +
	"rx_dropped\x18\a \x01(\x04R\trxDropped\x12\x1d\n" +
	"\n" +
	"tx_dropped\x18\b \x01(\x04R\ttxDropped\":\n" +
	"\n" +
	"GPUMetrics\x12,\n" +
	"\adevices\x18\x01 \x03(\v2\x12.metrics.GPUDeviceR\adevices\"\xf7\x01\n" +
	"\tGPUDevice\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04uuid\x18\x03 \x01(\tR\x04uuid\x12 \n" +
	"\vutilization\x18\x04 \x01(\x05R\vutilization\x12*\n" +
	"\x06memory\x18\x05 \x01(\v2\x12.metrics.GPUMemoryR\x06memory\x12 \n" +
	"\vtemperature\x18\x06 \x01(\x05R\vtemperature\x12\x1f\n" +
	"\vpower_usage\x18\a \x01(\x05R\n" +
	"powerUsage\x12\x1b\n" +
	"\tfan_speed\x18\b \x01(\x05R\bfanSpeed\"n\n" +
	"\tGPUMemory\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x04R\x04used\x12\x12\n" +
	"\x04free\x18\x03 \x01(\x04R\x04free\x12#\n" +
	"\rusage_percent\x18\x04 \x01(\x01R\fusagePercent\"\xc4\x02\n" +
	"\x0eProcessMetrics\x122\n" +
	"\tprocesses\x18\x01 \x03(\v2\x14.metrics.ProcessInfoR\tprocesses\x12-\n" +
	"\atop_cpu\x18\x02 \x03(\v2\x14.metrics.ProcessInfoR\x06topCpu\x123\n" +
	"\n" +
	"top_memory\x18\x03 \x03(\v2\x14.metrics.ProcessInfoR\ttopMemory\x12-\n" +
	"\atop_gpu\x18\x04 \x03(\v2\x14.metrics.ProcessInfoR\x06topGpu\x12\x1f\n" +
	"\vtotal_count\x18\x05 \x01(\x05R\n" +
	"totalCount\x12#\n" +
	"\rrunning_count\x18\x06 \x01(\x05R\frunningCount\x12%\n" +
	"\x0esleeping_count\x18\a \x01(\x05R\rsleepingCount\"\x92\f\n" +
	"\vProcessInfo\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x12\n" +
	"\x04ppid\x18\x02 \x01(\rR\x04ppid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\acommand\x18\x04 \x01(\tH\x00R\acommand\x88\x01\x01\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x1f\n" +
	"\vcpu_percent\x18\x06 \x01(\x01R\n" +
	"cpuPercent\x12%\n" +
	"\x0ememory_percent\x18\a \x01(\x01R\rmemoryPercent\x12\x1d\n" +
	"\n" +
	"memory_rss\x18\b \x01(\x04R\tmemoryRss\x12%\n" +
	"\x0ememory_virtual\x18\t \x01(\x04R\rmemoryVirtual\x12\x1f\n" +
	"\vnum_threads\x18\n" +
	" \x01(\rR\n" +
	"numThreads\x12\x1d\n" +
	"\n" +
	"read_bytes\x18\v \x01(\x04R\treadBytes\x12\x1f\n" +
	"\vwrite_bytes\x18\f \x01(\x04R\n" +
	"writeBytes\x12\"\n" +
	"\n" +
	"open_files\x18\r \x01(\rH\x01R\topenFiles\x88\x01\x01\x12(\n" +
	"\rsyscall_count\x18\x0e \x01(\x04H\x02R\fsyscallCount\x88\x01\x01\x12.\n" +
	"\x10context_switches\x18\x0f \x01(\x04H\x03R\x0fcontextSwitches\x88\x01\x01\x12\"\n" +
	"\n" +
	"gpu_memory\x18\x10 \x01(\x04H\x04R\tgpuMemory\x88\x01\x01\x12,\n" +
	"\x0fgpu_utilization\x18\x11 \x01(\x01H\x05R\x0egpuUtilization\x88\x01\x01\x12&\n" +
	"\fwait_channel\x18\x12 \x01(\tH\x06R\vwaitChannel\x88\x01\x01\x12\"\n" +
	"\n" +
	"wait_state\x18\x13 \x01(\tH\aR\twaitState\x88\x01\x01\x12%\n" +
	"\fwait_time_ms\x18\x14 \x01(\x04H\bR\n" +
	"waitTimeMs\x88\x01\x01\x120\n" +
	"\n" +
	"held_locks\x18\x15 \x03(\v2\x11.metrics.FileLockR\theldLocks\x126\n" +
	"\rwaiting_locks\x18\x16 \x03(\v2\x11.metrics.FileLockR\fwaitingLocks\x12,\n" +
	"\x0fblocked_threads\x18\x17 \x01(\rH\tR\x0eblockedThreads\x88\x01\x01\x129\n" +
	"\x16voluntary_ctx_switches\x18\x18 \x01(\x04H\n" +
	"R\x14voluntaryCtxSwitches\x88\x01\x01\x12=\n" +
	"\x18involuntary_ctx_switches\x18\x19 \x01(\x04H\vR\x16involuntaryCtxSwitches\x88\x01\x01\x12)\n" +
	"\x0ewaiting_on_pid\x18\x1a \x01(\rH\fR\fwaitingOnPid\x88\x01\x01\x12#\n" +
	"\rblocking_pids\x18\x1b \x03(\rR\fblockingPids\x12,\n" +
	"\x0fcurrent_syscall\x18\x1c \x01(\tH\rR\x0ecurrentSyscall\x88\x01\x01\x123\n" +
	"\x13syscall_duration_ms\x18\x1d \x01(\x04H\x0eR\x11syscallDurationMs\x88\x01\x01\x12*\n" +
	"\x0fio_wait_time_ms\x18\x1e \x01(\x04H\x0fR\fioWaitTimeMs\x88\x01\x01\x12)\n" +
	"\x0ecpu_time_delta\x18\x1f \x01(\x04H\x10R\fcpuTimeDelta\x88\x01\x01B\n" +
	"\n" +
	"\b_commandB\r\n" +
	"\v_open_filesB\x10\n" +
	"\x0e_syscall_countB\x13\n" +
	"\x11_context_switchesB\r\n" +
	"\v_gpu_memoryB\x12\n" +
	"\x10_gpu_utilizationB\x0f\n" +
	"\r_wait_channelB\r\n" +
	"\v_wait_stateB\x0f\n" +
	"\r_wait_time_msB\x12\n" +
	"\x10_blocked_threadsB\x19\n" +
	"\x17_voluntary_ctx_switchesB\x1b\n" +
	"\x19_involuntary_ctx_switchesB\x11\n" +
	"\x0f_waiting_on_pidB\x12\n" +
	"\x10_current_syscallB\x16\n" +
	"\x14_syscall_duration_msB\x12\n" +
	"\x10_io_wait_time_msB\x11\n" +
	"\x0f_cpu_time_delta\"c\n" +
	"\bFileLock\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tlock_type\x18\x02 \x01(\tR\blockType\x12\x14\n" +
	"\x05inode\x18\x03 \x01(\x04R\x05inode\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\rR\x03pid2\x92\x01\n" +
	"\x0eMetricsService\x12A\n" +
	"\rStreamMetrics\x12\x16.metrics.StreamRequest\x1a\x16.metrics.SystemMetrics0\x01\x12=\n" +
	"\n" +
	"GetMetrics\x12\x17.metrics.MetricsRequest\x1a\x16.metrics.SystemMetricsB\x1fZ\x1dsrc/system-eye/api/proto;protob\x06proto3"

var (
	file_src_system_eye_api_proto_metrics_proto_rawDescOnce sync.Once
	file_src_system_eye_api_proto_metrics_proto_rawDescData []byte
)

func file_src_system_eye_api_proto_metrics_proto_rawDescGZIP() []byte {
	file_src_system_eye_api_proto_metrics_proto_rawDescOnce.Do(func() {
		file_src_system_eye_api_proto_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_system_eye_api_proto_metrics_proto_rawDesc), len(file_src_system_eye_api_proto_metrics_proto_rawDesc)))
	})
	return file_src_system_eye_api_proto_metrics_proto_rawDescData
}

var file_src_system_eye_api_proto_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_src_system_eye_api_proto_metrics_proto_goTypes = []any{
	(*StreamRequest)(nil),         // 0: metrics.StreamRequest
	(*MetricsRequest)(nil),        // 1: metrics.MetricsRequest
	(*SystemMetrics)(nil),         // 2: metrics.SystemMetrics
	(*CPUMetrics)(nil),            // 3: metrics.CPUMetrics
	(*MemoryMetrics)(nil),         // 4: metrics.MemoryMetrics
	(*DiskMetrics)(nil),           // 5: metrics.DiskMetrics
	(*DiskDevice)(nil),            // 6: metrics.DiskDevice
	(*DiskIO)(nil),                // 7: metrics.DiskIO
	(*NetworkMetrics)(nil),        // 8: metrics.NetworkMetrics
	(*NetworkInterface)(nil),      // 9: metrics.NetworkInterface
	(*NetworkTraffic)(nil),        // 10: metrics.NetworkTraffic
	(*GPUMetrics)(nil),            // 11: metrics.GPUMetrics
	(*GPUDevice)(nil),             // 12: metrics.GPUDevice
	(*GPUMemory)(nil),             // 13: metrics.GPUMemory
	(*ProcessMetrics)(nil),        // 14: metrics.ProcessMetrics
	(*ProcessInfo)(nil),           // 15: metrics.ProcessInfo
	(*FileLock)(nil),              // 16: metrics.FileLock
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_src_system_eye_api_proto_metrics_proto_depIdxs = []int32{
	17, // 0: metrics.SystemMetrics.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 1: metrics.SystemMetrics.cpu:type_name -> metrics.CPUMetrics
	4,  // 2: metrics.SystemMetrics.memory:type_name -> metrics.MemoryMetrics
	5,  // 3: metrics.SystemMetrics.disk:type_name -> metrics.DiskMetrics
	8,  // 4: metrics.SystemMetrics.network:type_name -> metrics.NetworkMetrics
	11, // 5: metrics.SystemMetrics.gpu:type_name -> metrics.GPUMetrics
	14, // 6: metrics.SystemMetrics.processes:type_name -> metrics.ProcessMetrics
	6,  // 7: metrics.DiskMetrics.devices:type_name -> metrics.DiskDevice
	7,  // 8: metrics.DiskMetrics.total:type_name -> metrics.DiskIO
	7,  // 9: metrics.DiskDevice.io:type_name -> metrics.DiskIO
	9,  // 10: metrics.NetworkMetrics.interfaces:type_name -> metrics.NetworkInterface
	10, // 11: metrics.NetworkMetrics.total:type_name -> metrics.NetworkTraffic
	10, // 12: metrics.NetworkInterface.traffic:type_name -> metrics.NetworkTraffic
	12, // 13: metrics.GPUMetrics.devices:type_name -> metrics.GPUDevice
	13, // 14: metrics.GPUDevice.memory:type_name -> metrics.GPUMemory
	15, // 15: metrics.ProcessMetrics.processes:type_name -> metrics.ProcessInfo
	15, // 16: metrics.ProcessMetrics.top_cpu:type_name -> metrics.ProcessInfo
	15, // 17: metrics.ProcessMetrics.top_memory:type_name -> metrics.ProcessInfo
	15, // 18: metrics.ProcessMetrics.top_gpu:type_name -> metrics.ProcessInfo
	16, // 19: metrics.ProcessInfo.held_locks:type_name -> metrics.FileLock
	16, // 20: metrics.ProcessInfo.waiting_locks:type_name -> metrics.FileLock
	0,  // 21: metrics.MetricsService.StreamMetrics:input_type -> metrics.StreamRequest
	1,  // 22: metrics.MetricsService.GetMetrics:input_type -> metrics.MetricsRequest
	2,  // 23: metrics.MetricsService.StreamMetrics:output_type -> metrics.SystemMetrics
	2,  // 24: metrics.MetricsService.GetMetrics:output_type -> metrics.SystemMetrics
	23, // [23:25] is the sub-list for method output_type
	21, // [21:23] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_src_system_eye_api_proto_metrics_proto_init() }
func file_src_system_eye_api_proto_metrics_proto_init() {
	if File_src_system_eye_api_proto_metrics_proto != nil {
		return
	}
	file_src_system_eye_api_proto_metrics_proto_msgTypes[2].OneofWrappers = []any{}
	file_src_system_eye_api_proto_metrics_proto_msgTypes[7].OneofWrappers = []any{}
	file_src_system_eye_api_proto_metrics_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_system_eye_api_proto_metrics_proto_rawDesc), len(file_src_system_eye_api_proto_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_system_eye_api_proto_metrics_proto_goTypes,
		DependencyIndexes: file_src_system_eye_api_proto_metrics_proto_depIdxs,
		MessageInfos:      file_src_system_eye_api_proto_metrics_proto_msgTypes,
	}.Build()
	File_src_system_eye_api_proto_metrics_proto = out.File
	file_src_system_eye_api_proto_metrics_proto_goTypes = nil
	file_src_system_eye_api_proto_metrics_proto_depIdxs = nil
}
